name: build

on: [push, pull_request]

jobs:
  test:
    name: JDK ${{matrix.java}}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8]

    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Install dependencies
      run: |
        sudo apt-get install junit4 ant-optional curl
        curl -L https://github.com/licel/jcardsim/raw/jc2.2.2/jcardsim-2.2.2-all.jar -o test/lib/jcardsim-2.2.2-all.jar

    - name: Run tests
      run: ant -Dtest.build.mock=1 test
